### ISSUE TITLE
List of countries not shown in correct language

### ISSUE THREAD

**Issue by ojlaranjo** [ESPD/ESPD-Service#106] opened 2016-11-03 14:34 UTC
This issue came today from a user in Romania. In ESPD, after selecting Romanian as the language, once you go and chose your country, the list of countries does not show up in romanian, but instead in portuguese. Please see the image 1 attached.
![1](https://cloud.githubusercontent.com/assets/22073365/19969991/df4742b4-a1da-11e6-9957-5ea177dd73dd.jpg)

Don't know if this happens with all the other languages but possibly.

**Comment by dg-grow-virgiliu-ratoi** [comment] 2016-11-03 14:44
This is a duplicate of #84

**Closed by dg-grow-virgiliu-ratoi** 2016-11-03 14:44 UTC
Labels: bug
